'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MpSetting", [Namespace]:="http://schemas.datacontract.org/2004/07/XtraWcfWebHost"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MpSetting
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassMachinePackageControlField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassParameterField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PcsShotField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductionTimeField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StdLotQtyField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StdShotField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StdShotAutomotiveField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StopLongTimeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPassMachinePackageControl() As Boolean
            Get
                Return Me.IsPassMachinePackageControlField
            End Get
            Set
                If (Me.IsPassMachinePackageControlField.Equals(value) <> true) Then
                    Me.IsPassMachinePackageControlField = value
                    Me.RaisePropertyChanged("IsPassMachinePackageControl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPassParameter() As Boolean
            Get
                Return Me.IsPassParameterField
            End Get
            Set
                If (Me.IsPassParameterField.Equals(value) <> true) Then
                    Me.IsPassParameterField = value
                    Me.RaisePropertyChanged("IsPassParameter")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PcsShot() As Integer
            Get
                Return Me.PcsShotField
            End Get
            Set
                If (Me.PcsShotField.Equals(value) <> true) Then
                    Me.PcsShotField = value
                    Me.RaisePropertyChanged("PcsShot")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductionTime() As Double
            Get
                Return Me.ProductionTimeField
            End Get
            Set
                If (Me.ProductionTimeField.Equals(value) <> true) Then
                    Me.ProductionTimeField = value
                    Me.RaisePropertyChanged("ProductionTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StdLotQty() As Integer
            Get
                Return Me.StdLotQtyField
            End Get
            Set
                If (Me.StdLotQtyField.Equals(value) <> true) Then
                    Me.StdLotQtyField = value
                    Me.RaisePropertyChanged("StdLotQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StdShot() As Integer
            Get
                Return Me.StdShotField
            End Get
            Set
                If (Me.StdShotField.Equals(value) <> true) Then
                    Me.StdShotField = value
                    Me.RaisePropertyChanged("StdShot")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StdShotAutomotive() As Integer
            Get
                Return Me.StdShotAutomotiveField
            End Get
            Set
                If (Me.StdShotAutomotiveField.Equals(value) <> true) Then
                    Me.StdShotAutomotiveField = value
                    Me.RaisePropertyChanged("StdShotAutomotive")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StopLongTime() As Integer
            Get
                Return Me.StopLongTimeField
            End Get
            Set
                If (Me.StopLongTimeField.Equals(value) <> true) Then
                    Me.StopLongTimeField = value
                    Me.RaisePropertyChanged("StopLongTime")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IMpService")>  _
    Public Interface IMpService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMpService/MpCondition", ReplyAction:="http://tempuri.org/IMpService/MpConditionResponse")>  _
        Function MpCondition(ByVal McNo As String, ByVal Package As String, ByVal McType As String) As ServiceReference1.MpSetting
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMpService/MpCondition", ReplyAction:="http://tempuri.org/IMpService/MpConditionResponse")>  _
        Function MpConditionAsync(ByVal McNo As String, ByVal Package As String, ByVal McType As String) As System.Threading.Tasks.Task(Of ServiceReference1.MpSetting)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMpServiceChannel
        Inherits ServiceReference1.IMpService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MpServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IMpService)
        Implements ServiceReference1.IMpService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function MpCondition(ByVal McNo As String, ByVal Package As String, ByVal McType As String) As ServiceReference1.MpSetting Implements ServiceReference1.IMpService.MpCondition
            Return MyBase.Channel.MpCondition(McNo, Package, McType)
        End Function
        
        Public Function MpConditionAsync(ByVal McNo As String, ByVal Package As String, ByVal McType As String) As System.Threading.Tasks.Task(Of ServiceReference1.MpSetting) Implements ServiceReference1.IMpService.MpConditionAsync
            Return MyBase.Channel.MpConditionAsync(McNo, Package, McType)
        End Function
    End Class
End Namespace
